# -*- coding: utf-8 -*-
"""funcoes_python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SIWZmgqxLrpIncFDbfW7OnL9SfVqBqoB

# **Funções Python** ➿
"""

def name_function(arg1, arg2):      #Posso ou não ter argumentos  #Def: Define a função
 '''
 A documentação da sua função fica aqui
 '''
 #Nessa parte sua função executa o código
 return #Return: Retorna o resultado desejado

"""# **Função Sem Retorno**↪️"""

def hello():
  print("Hello world!")

hello()  #Print só funciona se a função é chamada

"""# **Função Com Argumentos/Parametros**🗣️"""

def maior(a, b):   #f-string: Pode inserir variáveis ou fazer cálculos diretamente dentro do texto, substituindo a variável pelo seu valor real na hora de imprimir
  if a > b:
    print(f"O número {a} é maior")  #Argumento: Qual é a maior
  else:
    print(f"O número {b} é maior")

maior(20, 100)

"""# **Escopo De Variáveis**🤯"""

def soma(x, y):
  total = x + y  #Essa variável chamamos de Local(Dentro da função)
  print(f"O total executado pela função é {total}")  #Pode ter duas variáveis pois uma ta dentro da função e a outra está fora(global)(escopo)

total = 20  #Essa variável chamamos de global

soma(6, 7)

print(f"O total principal é {total}")

"""# **Função Com Variável Global**🌏"""

def soma_numeros(x,y):
  global   #Serve para acessar a variável fora da função
  total1 = x + y
  print(total1)

soma_numeros(5, 2)
total1 = 10
soma_numeros(3, 8)
print(total1)

"""# **Função Com Retorno**↩️"""

#None: Nulo
def soma_com_return(a, b):
  total = a + b                       #Jeito Errado
  return

print(soma_com_return(10, 10))

def soma_com_return(a, b):
  total = a + b
  return total                      #Jeito Certo

resultado = soma_com_return(10, 10)

print(f"O resultado da função é {resultado}")

"""# **Função Com Parametro Fixo**🧮"""

def calcula_juros(valor, taxa=35):
  juros = valor*taxa/100
  return juros

calcula_juros(237)

teste = int(input("Cara, voce quer saber 35% de qual número?"))

def calcula_juros(valor, taxa=35):
  juros = valor*taxa/100
  return juros

valor = calcula_juros(teste)

print(valor)